# Generated by Django 5.1.6 on 2025-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="categories",
        ),
        migrations.AddField(
            model_name="category",
            name="words",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="core.word"
            ),
        ),
    ]
