# Generated by Django 5.1.6 on 2025-04-26 00:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_word_categories_category_words"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                to="core.category",
                verbose_name="Parent Categories",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("text"),
                name="word_text_ci_unique",
            ),
        ),
    ]
