# Generated by Django 5.2.4 on 2025-08-17 03:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("site_settings", "0010_alter_mapboxassistsettings_options"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Map Parameters"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Map Settings"
                    ),
                ),
                (
                    "map_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_pages",
                        to="site_settings.mapboxassistsettings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
