# Generated by Django 5.2.4 on 2025-08-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_mapboxassistsettings_mapboxassistfeaturelayer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappage",
            name="map_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_pages",
                to="map.mapboxassistsettings",
            ),
        ),
    ]
