# Generated by Django 5.2.4 on 2025-08-21 21:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_alter_mappage_map_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappage",
            name="help_panel_body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mappage",
            name="help_panel_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
