# Generated by Django 5.2.4 on 2025-08-29 00:35

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_mappage_help_panel_body_mappage_help_panel_title"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HikingPlannerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="MapboxAssistConfigs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("extra_head", models.TextField(blank=True)),
                (
                    "help_panel_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "help_panel_body",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Mapbox Assist Configurations",
                "verbose_name_plural": "Mapbox Assist Configurations",
            },
        ),
        migrations.CreateModel(
            name="MapboxSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                ("mapbox_api_version", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="mapboxassistfeaturelayer",
            name="set",
            field=modelcluster.fields.ParentalKey(
                help_text="Mapbox Assist settings to which this item belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_layers",
                to="map.mapboxassistconfigs",
                verbose_name="Feature Layer",
            ),
        ),
        migrations.AlterField(
            model_name="mapboxstyle",
            name="set",
            field=modelcluster.fields.ParentalKey(
                help_text="Define Mapbox styles. First item will load as default.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapbox_styles",
                to="map.mapboxassistconfigs",
                verbose_name="Mapbox Style",
            ),
        ),
        migrations.DeleteModel(
            name="MapPage",
        ),
        migrations.DeleteModel(
            name="MapboxAssistSettings",
        ),
    ]
