# Generated by Django 5.2.4 on 2025-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_hikingplannerpage_mapboxassistconfigs_mapboxsettings_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mapboxsettings",
            old_name="mapbox_api_version",
            new_name="api_version",
        ),
        migrations.AlterField(
            model_name="mapboxassistfeaturelayer",
            name="tile_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mapboxassistfeaturelayer",
            name="uid",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mapboxstyle",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mapboxstyle",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
