# Generated by Django 5.0.3 on 2024-04-04 04:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplevideoorderable",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
