# Generated by Django 5.0.3 on 2024-04-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_simplevideoorderable_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleVideoOrderable",
        ),
    ]
