# Generated by Django 5.0.3 on 2024-06-25 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_carouselimages_carousel_image"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimages",
            name="carousel_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carousel_image",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
    ]
