# Generated by Django 5.0.3 on 2024-06-30 04:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_spacecraft_imagedetailpagespacecraftorderable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spacecraft",
            old_name="spacecraft",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="imagedetailpagespacecraftorderable",
            name="spacecraft_name",
        ),
        migrations.AddField(
            model_name="imagedetailpagespacecraftorderable",
            name="spacecraft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spacecraft",
                to="blog.spacecraft",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imagedetailpagespacecraftorderable",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spacecrafts",
                to="blog.blogpage",
            ),
        ),
    ]
