# Generated by Django 5.0.3 on 2024-09-18 23:15

import blog.spacecraft
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_rename_spacecraft_spacecraft_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecraft",
            name="uuid",
            field=models.CharField(
                default=blog.spacecraft.generate_uuid, max_length=12, unique=True
            ),
        ),
    ]
