# Generated by Django 5.0.3 on 2024-10-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_affiliate_alter_blogpage_content_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliate_of",
                to="blog.company",
            ),
            preserve_default=False,
        ),
    ]
