# Generated by Django 5.0.3 on 2024-10-15 23:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_affiliate_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliate",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={},
        ),
        migrations.RenameField(
            model_name="company",
            old_name="type",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="company",
            name="affiliates",
        ),
        migrations.RemoveField(
            model_name="company",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="affiliate",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="affiliate",
            name="company",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliates",
                to="blog.company",
            ),
        ),
    ]
