# Generated by Django 5.1.6 on 2025-04-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_alter_blogpage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spacecraft",
            name="image",
        ),
        migrations.DeleteModel(
            name="ImageDetailPageSpacecraftOrderable",
        ),
        migrations.DeleteModel(
            name="Spacecraft",
        ),
    ]
