# Generated by Django 5.1.6 on 2025-05-12 02:52

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_remove_spacecraft_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="blog_pages",
                to="blog.blogcategory",
                verbose_name="Categories",
            ),
        ),
    ]
