# Generated by Django 4.2.2 on 2024-03-15 03:54

import blocks.import_text
import blocks.parsed_richtext
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("cleaned_rich_text", blocks.parsed_richtext.ParsedRichTextBlock()),
                    (
                        "csv_table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(required=True),
                                            ),
                                            (
                                                "heading_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("h2", "H2"),
                                                        ("h3", "H3"),
                                                        ("h4", "H4"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "alignment",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("justify", "Justified"),
                                                        ("start", "Left"),
                                                        ("center", "Centre"),
                                                        ("end", "Right"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "anchor_id",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Anchor identifier must be a compatible slug format without spaces or special characters",
                                                    label="Optional Anchor Identifier",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Table Title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "data",
                                    blocks.import_text.ImportTextBlock(
                                        file_type_filter=".csv",
                                        help_text="Paste in CSV data or import from .csv file",
                                        label="Comma Separated Data",
                                    ),
                                ),
                                (
                                    "precision",
                                    wagtail.blocks.IntegerBlock(
                                        default=2,
                                        help_text="Number of decimal places to display for float type.",
                                        label="Float Precision",
                                    ),
                                ),
                                (
                                    "column_headers",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="First row contains column headers",
                                        label="Column Headers",
                                        required=False,
                                    ),
                                ),
                                (
                                    "row_headers",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="First column contains row headers",
                                        label="Row Headers",
                                        required=False,
                                    ),
                                ),
                                (
                                    "compact",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Cell padding reduced by half",
                                        label="Compact Table Style",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        editor="minimal",
                                        help_text="Caption displayed beneath the table. Use as explanation or annotation.",
                                        label="Table Caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("justify", "Justified"),
                                            ("start", "Left"),
                                            ("center", "Centre"),
                                            ("end", "Right"),
                                        ],
                                        label="Caption Alignment",
                                        required=False,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.blocks.IntegerBlock(
                                        default=100,
                                        help_text="Table width (as percentage of container)",
                                        label="Table Width (%)",
                                    ),
                                ),
                                (
                                    "max_width",
                                    wagtail.blocks.IntegerBlock(
                                        help_text="Optional: Maximum width (in rem) the table can grow to",
                                        label="Maximum Table Width (rem)",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("import_text_block", blocks.import_text.ImportTextBlock()),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
    ]
