# Generated by Django 5.0.3 on 2024-04-04 04:18

import blocks.hidden
import blocks.import_text
import blocks.parsed_richtext
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("cleaned_rich_text", blocks.parsed_richtext.ParsedRichTextBlock()),
                    (
                        "csv_table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    label="Title", required=False
                                                ),
                                            ),
                                            (
                                                "heading_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("h3", "H3"),
                                                        ("h4", "H4"),
                                                        ("h5", "H5"),
                                                    ],
                                                    label="Size",
                                                ),
                                            ),
                                            (
                                                "alignment",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("justify", "Justified"),
                                                        ("start", "Left"),
                                                        ("center", "Centre"),
                                                        ("end", "Right"),
                                                    ],
                                                    label="Alignment",
                                                ),
                                            ),
                                            (
                                                "anchor_id",
                                                wagtail.blocks.CharBlock(
                                                    label="Optional Anchor Identifier",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Optional Table Title",
                                    ),
                                ),
                                (
                                    "data",
                                    blocks.import_text.ImportTextBlock(
                                        file_type_filter=".csv",
                                        help_text="Paste in CSV data or import from .csv file",
                                        label="Comma Separated Data",
                                    ),
                                ),
                                (
                                    "precision",
                                    wagtail.blocks.IntegerBlock(
                                        default=2, label="Float Precision"
                                    ),
                                ),
                                (
                                    "column_headers",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        label="Column Headers",
                                        required=False,
                                    ),
                                ),
                                (
                                    "row_headers",
                                    wagtail.blocks.BooleanBlock(
                                        label="Row Headers", required=False
                                    ),
                                ),
                                (
                                    "compact",
                                    wagtail.blocks.BooleanBlock(
                                        default=True, label="Compact", required=False
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        editor="minimal",
                                        help_text="Caption displayed beneath the table. Use as explanation or annotation.",
                                        label="Table Caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("justify", "Justified"),
                                            ("start", "Left"),
                                            ("center", "Centre"),
                                            ("end", "Right"),
                                        ],
                                        label="Caption Alignment",
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.blocks.IntegerBlock(
                                        default=100, label="Table Width (%)"
                                    ),
                                ),
                                (
                                    "max_width",
                                    wagtail.blocks.IntegerBlock(
                                        label="Maximum Table Width (rem)",
                                        required=False,
                                    ),
                                ),
                                ("html", blocks.hidden.HiddenCharBlock()),
                                (
                                    "rendered",
                                    blocks.hidden.HiddenBooleanBlock(default=True),
                                ),
                            ]
                        ),
                    ),
                    ("import_text_block", blocks.import_text.ImportTextBlock()),
                ],
                blank=True,
                verbose_name="Page body",
            ),
        ),
    ]
