# Generated by Django 4.2.2 on 2024-03-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_numericrange"),
    ]

    operations = [
        migrations.AddField(
            model_name="numericrange",
            name="title",
            field=models.CharField(default="hello"),
            preserve_default=False,
        ),
    ]
