# Generated by Django 4.2.2 on 2024-03-15 03:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_survey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={"verbose_name": "Survey"},
        ),
        migrations.AddField(
            model_name="survey",
            name="question_sets",
            field=wagtail.fields.StreamField(
                [
                    (
                        "question_set",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("condition", wagtail.blocks.TextBlock()),
                                (
                                    "questions",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "question",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "question",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "help_text",
                                                            wagtail.blocks.TextBlock(),
                                                        ),
                                                    ],
                                                    label="Text Question",
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                default=(),
                use_json_field=True,
                verbose_name="Question Sets",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="title",
            field=models.CharField(default="temp", verbose_name="Survey Label"),
            preserve_default=False,
        ),
    ]
