# Generated by Django 5.0.3 on 2024-04-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_alter_survey_options_survey_question_sets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokens",
            name="gmail_service_account",
            field=models.TextField(
                blank=True, null=True, verbose_name="Gmail Service Account Details"
            ),
        ),
    ]
