# Generated by Django 5.0.3 on 2024-04-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0006_tokens_gmail_service_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokens",
            name="site",
        ),
    ]
