# Generated by Django 5.0.3 on 2024-04-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0007_remove_tokens_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokens",
            name="gmail_service_account",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Gmail Service Account Details"
            ),
        ),
    ]
