# Generated by Django 5.2.4 on 2025-08-17 01:58

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0008_alter_tokens_gmail_service_account"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapboxAssistSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("mapbox_api_version", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MapboxAssistFeatureLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("uid", models.CharField(max_length=100, unique=True)),
                ("tile_id", models.CharField(max_length=100, unique=True)),
                ("handler_function_name", models.CharField(max_length=100)),
                ("handler_function_path", models.CharField(max_length=100)),
                (
                    "set",
                    modelcluster.fields.ParentalKey(
                        help_text="Mapbox Assist settings to which this item belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_layers",
                        to="site_settings.mapboxassistsettings",
                        verbose_name="Feature Layer",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MapboxStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("source", models.CharField(max_length=255, unique=True)),
                (
                    "set",
                    modelcluster.fields.ParentalKey(
                        help_text="Define Mapbox styles. First item will load as default.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapbox_styles",
                        to="site_settings.mapboxassistsettings",
                        verbose_name="Mapbox Style",
                    ),
                ),
                (
                    "tile_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Tile Image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
