# Generated by Django 5.2.4 on 2025-08-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_settings",
            "0009_mapboxassistsettings_mapboxassistfeaturelayer_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapboxassistsettings",
            options={
                "verbose_name": "Mapbox Assist Setting",
                "verbose_name_plural": "Mapbox Assist Settings",
            },
        ),
    ]
