# Generated by Django 5.2.4 on 2025-08-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0010_alter_mapboxassistsettings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mapboxstyle",
            name="set",
        ),
        migrations.RemoveField(
            model_name="mapboxstyle",
            name="tile_image",
        ),
        migrations.DeleteModel(
            name="MapboxAssistFeatureLayer",
        ),
        migrations.DeleteModel(
            name="MapboxAssistSettings",
        ),
        migrations.DeleteModel(
            name="MapboxStyle",
        ),
    ]
