# Generated by Django 4.1.5 on 2023-03-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("svg", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="svgicon",
            options={"verbose_name": "SVG Icon"},
        ),
    ]
