# Generated by Django 4.1.5 on 2023-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svg", "0004_rename_svgicon_svgimage_alter_svgimage_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="svgimage",
            name="tags",
        ),
        migrations.AlterField(
            model_name="svgimage",
            name="label",
            field=models.CharField(max_length=255, unique=True, verbose_name="label"),
        ),
        migrations.DeleteModel(
            name="SVGTag",
        ),
    ]
