# Generated by Django 4.1.7 on 2023-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svg", "0005_remove_svgimage_tags_alter_svgimage_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="svgimage",
            name="svg",
            field=models.TextField(
                help_text="Paste in SVG data, drag/drop or import from .svg file.<br>Height and width attributes will be stripped on save.",
                verbose_name="SVG",
            ),
        ),
    ]
