# Generated by Django 4.2.2 on 2023-10-25 00:18

import blocks.base_blocks
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    # replaces = [
    #     ("menu", "0001_initial"),
    #     ("menu", "0002_alter_menu_title"),
    #     ("menu", "0003_rename_icon_menu_image_alter_menu_items"),
    #     ("menu", "0004_alter_menu_options_menu_locale_menu_translation_key_and_more"),
    #     ("menu", "0005_alter_menu_unique_together_alter_menu_slug_and_more"),
    #     ("menu", "0006_remove_menu_image_menu_logo"),
    #     ("menu", "0007_alter_menu_items"),
    #     ("menu", "0008_alter_menu_items"),
    #     ("menu", "0009_alter_menu_items"),
    #     ("menu", "0010_alter_menu_items"),
    #     ("menu", "0011_alter_menu_items"),
    #     ("menu", "0012_alter_menu_items"),
    #     ("menu", "0013_menu_expire_at_menu_expired_menu_first_published_at_and_more"),
    #     ("menu", "0014_menu_locked_menu_locked_at_menu_locked_by"),
    #     ("menu", "0015_menu_locale_menu_translation_key_and_more"),
    #     ("menu", "0016_menu_breakpoint"),
    #     ("menu", "0017_alter_menu_breakpoint"),
    #     ("menu", "0018_alter_menu_unique_together_remove_menu_locale_and_more"),
    #     ("menu", "0019_alter_menu_items"),
    #     ("menu", "0020_alter_menu_items"),
    #     ("menu", "0021_alter_menu_items"),
    #     ("menu", "0022_alter_menu_items"),
    # ]

    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        # ("wagtailcore", "0090_merge_20230906_1218"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("svg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Menu Title")),
                ("slug", models.SlugField(unique=True)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [
                            (
                                "internal_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            blocks.base_blocks.ImageChooserBlock(
                                                label="Optional image for display",
                                                required=False,
                                                widget_attrs={"show_edit_link": False},
                                            ),
                                        ),
                                        (
                                            "display_when",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("ALWAYS", "Always"),
                                                    ("True", "When logged in"),
                                                    ("False", "When not logged in"),
                                                ],
                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                label=None,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "page",
                                            blocks.data_blocks.DataPageChooserBlock(
                                                widget_attrs={"show_edit_link": False}
                                            ),
                                        ),
                                        (
                                            "display_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Leave blank to use page title.",
                                                label="Optional Text to Display on Menu",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            blocks.base_blocks.ImageChooserBlock(
                                                label="Optional image for display",
                                                required=False,
                                                widget_attrs={"show_edit_link": False},
                                            ),
                                        ),
                                        (
                                            "display_when",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("ALWAYS", "Always"),
                                                    ("True", "When logged in"),
                                                    ("False", "When not logged in"),
                                                ],
                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                label=None,
                                                required=False,
                                            ),
                                        ),
                                        ("url", wagtail.blocks.URLBlock()),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Text to Display on Menu",
                                                max_length=255,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "autofill_menu",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            blocks.base_blocks.ImageChooserBlock(
                                                label="Optional image for display",
                                                required=False,
                                                widget_attrs={"show_edit_link": False},
                                            ),
                                        ),
                                        (
                                            "display_when",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("ALWAYS", "Always"),
                                                    ("True", "When logged in"),
                                                    ("False", "When not logged in"),
                                                ],
                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                label=None,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Text to Display on Menu",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "parent_page",
                                            blocks.data_blocks.DataPageChooserBlock(),
                                        ),
                                        (
                                            "include_parent_page",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                                required=False,
                                                verbose_name="Include Parent Page in Sub-Menu",
                                            ),
                                        ),
                                        (
                                            "only_show_in_menus",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                                required=False,
                                                verbose_name="Include only 'Show In Menu' pages",
                                            ),
                                        ),
                                        (
                                            "order_by",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "-last_published_at",
                                                        "Newest (by most recently updated)",
                                                    ),
                                                    (
                                                        "-first_published_at",
                                                        "Newest to Oldest (by date originally published)",
                                                    ),
                                                    (
                                                        "first_published_at",
                                                        "Oldest to Newest",
                                                    ),
                                                    ("title", "Title (A-Z)"),
                                                ],
                                                help_text="Choose the order in which to show results",
                                                label=None,
                                            ),
                                        ),
                                        (
                                            "max_items",
                                            wagtail.blocks.IntegerBlock(
                                                blank=False,
                                                default=4,
                                                help_text="Maximum results to display in the menu",
                                                min_value=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "sub_menu",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            blocks.base_blocks.ImageChooserBlock(
                                                label="Optional image for display",
                                                required=False,
                                                widget_attrs={"show_edit_link": False},
                                            ),
                                        ),
                                        (
                                            "display_when",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("ALWAYS", "Always"),
                                                    ("True", "When logged in"),
                                                    ("False", "When not logged in"),
                                                ],
                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                label=None,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Text to Display on Menu",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "links",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "icon",
                                                                    blocks.base_blocks.ImageChooserBlock(
                                                                        label="Optional image for display",
                                                                        required=False,
                                                                        widget_attrs={
                                                                            "show_edit_link": False
                                                                        },
                                                                    ),
                                                                ),
                                                                (
                                                                    "display_when",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "ALWAYS",
                                                                                "Always",
                                                                            ),
                                                                            (
                                                                                "True",
                                                                                "When logged in",
                                                                            ),
                                                                            (
                                                                                "False",
                                                                                "When not logged in",
                                                                            ),
                                                                        ],
                                                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                        label=None,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "page",
                                                                    blocks.data_blocks.DataPageChooserBlock(
                                                                        widget_attrs={
                                                                            "show_edit_link": False
                                                                        }
                                                                    ),
                                                                ),
                                                                (
                                                                    "display_title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Leave blank to use page title.",
                                                                        label="Optional Text to Display on Menu",
                                                                        max_length=255,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "icon",
                                                                    blocks.base_blocks.ImageChooserBlock(
                                                                        label="Optional image for display",
                                                                        required=False,
                                                                        widget_attrs={
                                                                            "show_edit_link": False
                                                                        },
                                                                    ),
                                                                ),
                                                                (
                                                                    "display_when",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "ALWAYS",
                                                                                "Always",
                                                                            ),
                                                                            (
                                                                                "True",
                                                                                "When logged in",
                                                                            ),
                                                                            (
                                                                                "False",
                                                                                "When not logged in",
                                                                            ),
                                                                        ],
                                                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                        label=None,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.URLBlock(),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Text to Display on Menu",
                                                                        max_length=255,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "autofill_submenu",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "icon",
                                                                    blocks.base_blocks.ImageChooserBlock(
                                                                        label="Optional image for display",
                                                                        required=False,
                                                                        widget_attrs={
                                                                            "show_edit_link": False
                                                                        },
                                                                    ),
                                                                ),
                                                                (
                                                                    "display_when",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "ALWAYS",
                                                                                "Always",
                                                                            ),
                                                                            (
                                                                                "True",
                                                                                "When logged in",
                                                                            ),
                                                                            (
                                                                                "False",
                                                                                "When not logged in",
                                                                            ),
                                                                        ],
                                                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                        label=None,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Text to Display on Menu",
                                                                        max_length=255,
                                                                    ),
                                                                ),
                                                                (
                                                                    "parent_page",
                                                                    blocks.data_blocks.DataPageChooserBlock(),
                                                                ),
                                                                (
                                                                    "include_parent_page",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=False,
                                                                        help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                                                        required=False,
                                                                        verbose_name="Include Parent Page in Sub-Menu",
                                                                    ),
                                                                ),
                                                                (
                                                                    "only_show_in_menus",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=False,
                                                                        help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                                                        required=False,
                                                                        verbose_name="Include only 'Show In Menu' pages",
                                                                    ),
                                                                ),
                                                                (
                                                                    "order_by",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "-last_published_at",
                                                                                "Newest (by most recently updated)",
                                                                            ),
                                                                            (
                                                                                "-first_published_at",
                                                                                "Newest to Oldest (by date originally published)",
                                                                            ),
                                                                            (
                                                                                "first_published_at",
                                                                                "Oldest to Newest",
                                                                            ),
                                                                            (
                                                                                "title",
                                                                                "Title (A-Z)",
                                                                            ),
                                                                        ],
                                                                        help_text="Choose the order in which to show results",
                                                                        label=None,
                                                                    ),
                                                                ),
                                                                (
                                                                    "max_items",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        blank=False,
                                                                        default=4,
                                                                        help_text="Maximum results to display in the menu",
                                                                        min_value=1,
                                                                    ),
                                                                ),
                                                                (
                                                                    "open_direction",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "end",
                                                                                "Open items to the right",
                                                                            ),
                                                                            (
                                                                                "start",
                                                                                "Open items to the left",
                                                                            ),
                                                                            (
                                                                                "inline",
                                                                                "Expand submenu inline (accordian)",
                                                                            ),
                                                                        ],
                                                                        help_text="Choose submenu direction.",
                                                                        label=None,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Menu Items",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Optional Menu Title Logo",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
                (
                    "breakpoint",
                    models.CharField(
                        choices=[
                            ("md", "Small Screens (<768px)"),
                            ("lg", "Medium Screens (<992px)"),
                        ],
                        default="lg",
                        max_length=4,
                        null=True,
                        verbose_name="Mobile Layout Breakpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
            },
        ),
    ]
