# Generated by Django 4.2.2 on 2023-11-05 00:03

import blocks.base_blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0027_alter_menu_breakpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "internal_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.ImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    blocks.data_blocks.DataPageChooserBlock(
                                        widget_attrs={"show_edit_link": False}
                                    ),
                                ),
                                (
                                    "display_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use page title.",
                                        label="Optional Text to Display on Menu",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu after collapse in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.ImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                ("url", wagtail.blocks.URLBlock()),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=255
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu after collapse in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "autofill_menu",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.ImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=255
                                    ),
                                ),
                                (
                                    "parent_page",
                                    blocks.data_blocks.DataPageChooserBlock(),
                                ),
                                (
                                    "include_parent_page",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                        required=False,
                                        verbose_name="Include Parent Page in Sub-Menu",
                                    ),
                                ),
                                (
                                    "only_show_in_menus",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                        required=False,
                                        verbose_name="Include only 'Show In Menu' pages",
                                    ),
                                ),
                                (
                                    "order_by",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "-last_published_at",
                                                "Newest (by most recently updated)",
                                            ),
                                            (
                                                "-first_published_at",
                                                "Newest to Oldest (by date originally published)",
                                            ),
                                            ("first_published_at", "Oldest to Newest"),
                                            ("title", "Title (A-Z)"),
                                        ],
                                        help_text="Choose the order in which to show results",
                                        label=None,
                                    ),
                                ),
                                (
                                    "max_items",
                                    wagtail.blocks.IntegerBlock(
                                        blank=False,
                                        default=4,
                                        help_text="Maximum results to display in the menu",
                                        min_value=1,
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu after collapse in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "sub_menu",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.ImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=255
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu after collapse in mobile view",
                                        required=False,
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.ImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            blocks.data_blocks.DataPageChooserBlock(
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                }
                                                            ),
                                                        ),
                                                        (
                                                            "display_title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Leave blank to use page title.",
                                                                label="Optional Text to Display on Menu",
                                                                max_length=255,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.ImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text to Display on Menu",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "autofill_submenu",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.ImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text to Display on Menu",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                        (
                                                            "parent_page",
                                                            blocks.data_blocks.DataPageChooserBlock(),
                                                        ),
                                                        (
                                                            "include_parent_page",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                                                required=False,
                                                                verbose_name="Include Parent Page in Sub-Menu",
                                                            ),
                                                        ),
                                                        (
                                                            "only_show_in_menus",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                                                required=False,
                                                                verbose_name="Include only 'Show In Menu' pages",
                                                            ),
                                                        ),
                                                        (
                                                            "order_by",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "-last_published_at",
                                                                        "Newest (by most recently updated)",
                                                                    ),
                                                                    (
                                                                        "-first_published_at",
                                                                        "Newest to Oldest (by date originally published)",
                                                                    ),
                                                                    (
                                                                        "first_published_at",
                                                                        "Oldest to Newest",
                                                                    ),
                                                                    (
                                                                        "title",
                                                                        "Title (A-Z)",
                                                                    ),
                                                                ],
                                                                help_text="Choose the order in which to show results",
                                                                label=None,
                                                            ),
                                                        ),
                                                        (
                                                            "max_items",
                                                            wagtail.blocks.IntegerBlock(
                                                                blank=False,
                                                                default=4,
                                                                help_text="Maximum results to display in the menu",
                                                                min_value=1,
                                                            ),
                                                        ),
                                                        (
                                                            "open_direction",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "end",
                                                                        "Open items to the right",
                                                                    ),
                                                                    (
                                                                        "start",
                                                                        "Open items to the left",
                                                                    ),
                                                                    (
                                                                        "inline",
                                                                        "Expand submenu inline (accordian)",
                                                                    ),
                                                                ],
                                                                help_text="Choose submenu direction.",
                                                                label=None,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "search_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.ImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=255
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu after collapse in mobile view",
                                        required=False,
                                    ),
                                ),
                            ],
                            max_num=1,
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Menu Items",
            ),
        ),
    ]
