# Generated by Django 4.2.2 on 2024-02-21 23:50

import blocks.base_blocks
from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0045_alter_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.CustomImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    blocks.data_blocks.DataPageChooserBlock(
                                        widget_attrs={"show_edit_link": False}
                                    ),
                                ),
                                (
                                    "display_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use page title.",
                                        label="Optional Text to Display on Menu",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu bar in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "url_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.CustomImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                ("url", blocks.base_blocks.ExtendedURLBlock(label="URL")),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=255
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu bar in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "link_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("page", "Page Link"),
                                            ("url", "URL Link"),
                                            ("document", "Document Link"),
                                        ],
                                        label="",
                                        required=False,
                                    ),
                                ),
                                (
                                    "internal_page",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link to internal page", required=False
                                    ),
                                ),
                                (
                                    "anchor_target",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor target must start with '#' followed by alphanumeric characters, hyphens and underscores.",
                                        label="Optional anchor target",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url_link",
                                    blocks.base_blocks.ExtendedURLBlock(
                                        label="Link to external site or internal URL",
                                        required=False,
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        label="Link to document", required=False
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        label="Link text", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "r_submenu",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "sub_menu",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "items",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "sub_menu",
                                                                        wagtail.blocks.StreamBlock(
                                                                            [
                                                                                (
                                                                                    "items",
                                                                                    wagtail.blocks.Block(),
                                                                                )
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "link_type",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=[
                                                                                            (
                                                                                                "page",
                                                                                                "Page Link",
                                                                                            ),
                                                                                            (
                                                                                                "url",
                                                                                                "URL Link",
                                                                                            ),
                                                                                            (
                                                                                                "document",
                                                                                                "Document Link",
                                                                                            ),
                                                                                        ],
                                                                                        label="",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "internal_page",
                                                                                    wagtail.blocks.PageChooserBlock(
                                                                                        label="Link to internal page",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "anchor_target",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        help_text="Anchor target must start with '#' followed by alphanumeric characters, hyphens and underscores.",
                                                                                        label="Optional anchor target",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "url_link",
                                                                                    blocks.base_blocks.ExtendedURLBlock(
                                                                                        label="Link to external site or internal URL",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "document",
                                                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                                                        label="Link to document",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "link_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        label="Link text",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "link_type",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "page",
                                                                        "Page Link",
                                                                    ),
                                                                    ("url", "URL Link"),
                                                                    (
                                                                        "document",
                                                                        "Document Link",
                                                                    ),
                                                                ],
                                                                label="",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "internal_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Link to internal page",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "anchor_target",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Anchor target must start with '#' followed by alphanumeric characters, hyphens and underscores.",
                                                                label="Optional anchor target",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url_link",
                                                            blocks.base_blocks.ExtendedURLBlock(
                                                                label="Link to external site or internal URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "document",
                                                            wagtail.documents.blocks.DocumentChooserBlock(
                                                                label="Link to document",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(
                                                                label="Link text",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "autofill_menu",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.CustomImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=50
                                    ),
                                ),
                                (
                                    "parent_page",
                                    blocks.data_blocks.DataPageChooserBlock(),
                                ),
                                (
                                    "include_parent_page",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                        required=False,
                                        verbose_name="Include Parent Page in Sub-Menu",
                                    ),
                                ),
                                (
                                    "only_show_in_menus",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                        required=False,
                                        verbose_name="Include only 'Show In Menu' pages",
                                    ),
                                ),
                                (
                                    "order_by",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "-last_published_at",
                                                "Newest (by most recently updated)",
                                            ),
                                            (
                                                "-first_published_at",
                                                "Newest to Oldest (by date originally published)",
                                            ),
                                            ("first_published_at", "Oldest to Newest"),
                                            ("title", "Title (A-Z)"),
                                        ],
                                        help_text="Choose the order in which to show results",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "max_items",
                                    wagtail.blocks.IntegerBlock(
                                        blank=False,
                                        default=4,
                                        help_text="Maximum results to display in the menu",
                                        min_value=1,
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu bar in mobile view",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "sub_menu",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    blocks.base_blocks.CustomImageChooserBlock(
                                        label="Optional image for display",
                                        required=False,
                                        widget_attrs={"show_edit_link": False},
                                    ),
                                ),
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                ),
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu bar in mobile view",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Text to Display on Menu", max_length=50
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "page_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.CustomImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            blocks.data_blocks.DataPageChooserBlock(
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                }
                                                            ),
                                                        ),
                                                        (
                                                            "display_title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Leave blank to use page title.",
                                                                label="Optional Text to Display on Menu",
                                                                max_length=255,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "url_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.CustomImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            blocks.base_blocks.ExtendedURLBlock(
                                                                label="URL"
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text to Display on Menu",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "autofill_submenu",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.CustomImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text to Display on Menu",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "parent_page",
                                                            blocks.data_blocks.DataPageChooserBlock(),
                                                        ),
                                                        (
                                                            "include_parent_page",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                help_text="If selected, linked page will included before auto-filled items followed by dividing line",
                                                                required=False,
                                                                verbose_name="Include Parent Page in Sub-Menu",
                                                            ),
                                                        ),
                                                        (
                                                            "only_show_in_menus",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                help_text="If selected, only child pages with 'Show In Menu' selected will be shown.",
                                                                required=False,
                                                                verbose_name="Include only 'Show In Menu' pages",
                                                            ),
                                                        ),
                                                        (
                                                            "order_by",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "-last_published_at",
                                                                        "Newest (by most recently updated)",
                                                                    ),
                                                                    (
                                                                        "-first_published_at",
                                                                        "Newest to Oldest (by date originally published)",
                                                                    ),
                                                                    (
                                                                        "first_published_at",
                                                                        "Oldest to Newest",
                                                                    ),
                                                                    (
                                                                        "title",
                                                                        "Title (A-Z)",
                                                                    ),
                                                                ],
                                                                help_text="Choose the order in which to show results",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "max_items",
                                                            wagtail.blocks.IntegerBlock(
                                                                blank=False,
                                                                default=4,
                                                                help_text="Maximum results to display in the menu",
                                                                min_value=1,
                                                            ),
                                                        ),
                                                        (
                                                            "open_direction",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "end",
                                                                        "Open items to the right",
                                                                    ),
                                                                    (
                                                                        "start",
                                                                        "Open items to the left",
                                                                    ),
                                                                    (
                                                                        "inline",
                                                                        "Expand submenu inline (accordian)",
                                                                    ),
                                                                ],
                                                                help_text="Choose submenu direction.",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "search_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "display_when",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("ALWAYS", "Always"),
                                            ("True", "When logged in"),
                                            ("False", "When not logged in"),
                                        ],
                                        help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                        label=None,
                                        required=False,
                                    ),
                                )
                            ],
                            max_num=1,
                        ),
                    ),
                    (
                        "user_menu",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "sticky",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Item remains on menu bar in mobile view",
                                        required=False,
                                    ),
                                ),
                                (
                                    "logged_in_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Menu title when user is logged in.",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "logged_in_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Message to display to logged in users. Use @username or @display_name to display those values inline.",
                                        max_length=150,
                                        required=False,
                                    ),
                                ),
                                (
                                    "logged_out_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Menu title when user is not logged in.",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "page_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.CustomImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            blocks.data_blocks.DataPageChooserBlock(
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                }
                                                            ),
                                                        ),
                                                        (
                                                            "display_title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Leave blank to use page title.",
                                                                label="Optional Text to Display on Menu",
                                                                max_length=255,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "url_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            blocks.base_blocks.CustomImageChooserBlock(
                                                                label="Optional image for display",
                                                                required=False,
                                                                widget_attrs={
                                                                    "show_edit_link": False
                                                                },
                                                            ),
                                                        ),
                                                        (
                                                            "display_when",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "ALWAYS",
                                                                        "Always",
                                                                    ),
                                                                    (
                                                                        "True",
                                                                        "When logged in",
                                                                    ),
                                                                    (
                                                                        "False",
                                                                        "When not logged in",
                                                                    ),
                                                                ],
                                                                help_text="Determines if menu item is only shown if user logged in, logged out or always",
                                                                label=None,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            blocks.base_blocks.ExtendedURLBlock(
                                                                label="URL"
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text to Display on Menu",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            max_num=1,
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Menu Items",
            ),
        ),
    ]
