# Generated by Django 5.0.3 on 2024-11-13 03:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0053_alter_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    ("submenu", 28),
                    ("autofill_menu", 30),
                    ("link", 32),
                    ("search_form", 35),
                    ("user_menu", 44),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Submenu Display Title", "max_length": 50},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page Link"),
                                ("url_link", "URL Link"),
                            ],
                            "label": "Link Type",
                        },
                    ),
                    2: (
                        "blocks.data_blocks.DataPageChooserBlock",
                        (),
                        {
                            "attrs": {"data-link-block-type": "page"},
                            "chooser_attrs": {"show_edit_link": False},
                            "label": "Link to internal page",
                            "required": False,
                        },
                    ),
                    3: (
                        "blocks.data_blocks.DataCharBlock",
                        (),
                        {
                            "attrs": {"data-link-block-type": "page"},
                            "label": "Optional anchor target (#)",
                            "required": False,
                        },
                    ),
                    4: (
                        "blocks.data_blocks.DataExtendedURLBlock",
                        (),
                        {
                            "attrs": {"data-link-block-type": "url_link"},
                            "label": "Link to external site or internal URL",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("anchor_target", 3),
                                ("url_link", 4),
                                ("link_text", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "blocks.base_blocks.CustomImageChooserBlock",
                        (),
                        {
                            "chooser_attrs": {"show_edit_link": False},
                            "form_classname": "compact-image-chooser",
                            "label": "Optional menu icon",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ALWAYS", "Always"),
                                ("True", "Logged in"),
                                ("False", "Not logged in"),
                            ],
                            "help_text": "Shown if user logged in, logged out or always",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Menu Link Options",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 6), ("options", 9)]],
                        {"link_types": ["page", "url_link"]},
                    ),
                    11: ("menu.blocks.SubMenuDividerBlock", (), {}),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("link", 10), ("divider", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Sub Menu Options",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 12), ("options", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Submenu Label", "max_length": 50},
                    ),
                    16: (
                        "blocks.base_blocks.CustomPageChooserBlock",
                        (),
                        {
                            "form_classname": "autofill-parent-page",
                            "label": "Parent Page",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "-first_published_at",
                                    "Newest to Oldest (by date originally published)",
                                ),
                                (
                                    "first_published_at",
                                    "Oldest to Newest (by date originally published)",
                                ),
                                (
                                    "-last_published_at",
                                    "Newest to Oldest (by date of last update)",
                                ),
                                (
                                    "last_published_at",
                                    "Oldest to Newest (by date of last update)",
                                ),
                                ("title", "Title (A-Z)"),
                            ],
                            "help_text": "Choose the order in which to show results",
                            "label": "Order By",
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If selected, linked page will included before auto-filled items followed by dividing line",
                            "label": "Include Parent Page in Submenu",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If selected, only child pages with 'Show In Menu' selected will be shown.",
                            "label": "Only 'Show In Menu' Pages",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "blank": False,
                            "default": 4,
                            "help_text": "Maximum number of results to display in the menu",
                            "label": "Maximum Items",
                            "min_value": 1,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Auto Page Links Submenu Options",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("parent_page", 16),
                                ("order_by", 17),
                                ("include_parent_page", 18),
                                ("only_show_in_menus", 19),
                                ("max_items", 20),
                                ("options", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("sub_menu", 14),
                                ("autofill_submenu", 22),
                                ("link", 10),
                                ("divider", 11),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 23), ("options", 13)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("sub_menu", 24),
                                ("autofill_submenu", 22),
                                ("link", 10),
                                ("divider", 11),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Item remains on menu bar in mobile view",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8), ("sticky", 26)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Sub Menu Options",
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 25), ("options", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8), ("sticky", 26)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Auto Page Links Submenu Options",
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("parent_page", 16),
                                ("order_by", 17),
                                ("include_parent_page", 18),
                                ("only_show_in_menus", 19),
                                ("max_items", 20),
                                ("options", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8), ("sticky", 26)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Menu Link Options",
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 6), ("options", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Menu label", "max_length": 20},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 7), ("display_when", 8), ("sticky", 26)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "Search Form Options",
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 33), ("options", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu title when user is logged in.",
                            "max_length": 50,
                        },
                    ),
                    37: (
                        "blocks.base_blocks.CustomImageChooserBlock",
                        (),
                        {
                            "chooser_attrs": {"show_edit_link": False},
                            "form_classname": "compact-image-chooser",
                            "label": "Optional icon when logged in",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Message to display to logged in users.              Use @username or @display_name to display those values inline.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu title when user is not logged in.",
                            "max_length": 50,
                        },
                    ),
                    40: (
                        "blocks.base_blocks.CustomImageChooserBlock",
                        (),
                        {
                            "chooser_attrs": {"show_edit_link": False},
                            "form_classname": "compact-image-chooser",
                            "label": "Optional icon when logged out",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 6), ("options", 9)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (41,),
                        {"label": "User Menu Links"},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("sticky", 26)]],
                        {
                            "form_classname": "structblock menu-item-options",
                            "label": "User Menu Options",
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logged_in_title", 36),
                                ("logged_in_icon", 37),
                                ("logged_in_text", 38),
                                ("logged_out_title", 39),
                                ("logged_out_icon", 40),
                                ("items", 42),
                                ("options", 43),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Menu Items",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
