# Generated by Django 5.0.3 on 2024-05-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("front_editor", "0003_post_created_at_post_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
    ]
