# Generated by Django 5.0.3 on 2024-05-22 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front_editor", "0006_post_posts_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="posts_page",
        ),
        migrations.AddField(
            model_name="post",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="front_editor.postspage",
            ),
        ),
    ]
