# Generated by Django 5.0.3 on 2024-06-05 04:52

import django_quill2.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("front_editor", "0009_remove_post_draftail_post_tiptap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill2.fields.QuillField(),
        ),
    ]
