# Generated by Django 5.0.3 on 2024-06-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("front_editor", "0010_alter_post_content"),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name="post",
    #         name="tiptap",
    #     ),
    # ]
